### ISSUE TITLE
Ahem

### ISSUE THREAD

**Issue by 0xBRM** [Gitoffthelawn/uBlock-Deluxe#1]
... is this the intended result, or did I do something wrong? It looks almost exactly the same, save for the icon.

![untitled](https://cloud.githubusercontent.com/assets/9098352/7940759/c2431974-094a-11e5-9c37-1a58c689a6eb.png)

Went to ~/.mozilla/firefox/<profile folder>/chrome/userChrome.css, put the uBlock css overlay there, restarted firefox.

**Comment by Gitoffthelawn** [comment]
No, that's not it.  Try putting userChrome.css in your profile folder, not in the Firefox application folder.  Write back if that works; if not we can troubleshoot some more.

**Comment by 0xBRM** [comment]
Well yes, for some reason github removed '<profile folder>'. The location was correct.

**Comment by Gitoffthelawn** [comment]
Probably the markdown editor grabbing text.  Did you get it working, or not yet?  I have a few minutes I can troubleshoot right now.

**Comment by Gitoffthelawn** [comment]
I changed the format of the files.  Give it a try again... it should work for you now.  Thanks for bringing this to my attention.

**Comment by 0xBRM** [comment]
![untitled](https://cloud.githubusercontent.com/assets/9098352/7946564/436a1286-096f-11e5-9f32-83ea385b7da2.png)

Yup, it's definitely working now.

**Comment by Gitoffthelawn** [comment]
Great!  Also take a look at the dashboard by clicking on the dark uBlock title bar near the top of the popup.
